[wokwi]
version = 1
firmware = ".pio/build/fm-devkit/firmware.bin"
elf = ".pio/build/fm-devkit/firmware.elf"
gdbServerPort = 3333

[[chip]]
name = "chip-mh-z19"
binary = "chip-mh-z19.chip.wasm"

[[chip]]
name = "chip-moisture-sensor"
binary = "chip-moisture-sensor.chip.wasm"